FROM golang:1.21

WORKDIR /app

COPY go.mod .
COPY go.sum .

RUN go mod download
RUN go mod tidy

COPY . .

RUN go build ./cmd/main.go

WORKDIR /app

ARG GITHUB_SHA
ARG GITHUB_REPOSITORY
ARG GITHUB_REPOSITORY_URL

ENV GITHUB_SHA=${GITHUB_SHA}
ENV GITHUB_REPOSITORY=${GITHUB_REPOSITORY}
ENV GITHUB_REPOSITORY_URL=${GITHUB_REPOSITORY_URL}

ENTRYPOINT ["./main"]