#!/bin/bash
echo "Pre-push checks!"
cd back || exit 1
# Run backend unit tests
echo "Running backend unit tests"
go test -short ./...
status=$?
if test $status -eq 0; then
  echo "backend test success"
else
  echo "backend test failed"
  exit 1
fi

