name: Build and Push Backend Docker Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - id: repository_owner
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.repository_owner }}

      - id: repository_name
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.event.repository.name }}

      - name: Build image
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          build-args: GITHUB_SHA=${{github.sha}} GITHUB_REPOSITORY=${{github.repository}} GITHUB_REPOSITORY_URL=${{github.repositoryUrl}}
          context: ./back
          platforms: linux/amd64,linux/arm64
          file: ./back/Dockerfile
          push: true
          tags: ghcr.io/${{ steps.repository_owner.outputs.lowercase }}/${{ steps.repository_name.outputs.lowercase }}-back:latest
          no-cache: true